import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import ResponsiveContext from "./components/ResponsiveContext";
import FloatingContactButtons from "./components/FloatingContactButtons";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="fa">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar />
        <ResponsiveContext>{children}</ResponsiveContext>
        <Footer />
        <FloatingContactButtons />
      </body>
    </html>
  );
}
